### ISSUE TITLE
Toast Hides along with the spinner in IOS

### ISSUE THREAD

**Issue by ahadali** [vonovak/react-native-simple-toast#16]
I am using react-native-loading-spinner-overlay library for generating spinners in my app. I have several conditions where I need to show Toast after the spinner has stopped spinning but the Toast disappears immediately(in just one second) after the spinner has stopped. I am facing this issue in IOS only, in Android both Toast and spinners are working correctly.

**Comment by NitheeshDevadiga** [comment]
even I m facing the same issue.... any solution?

**Comment by ahadali** [comment]
@NitheeshDevadiga there is an alternative solution for this, you can install another library called react-native-root-toast [link here](https://www.npmjs.com/package/react-native-root-toast). This library works fine on both Android and IOS.

**Comment by NitheeshDevadiga** [comment]
Thanks for the solution. It's working now.

**Comment by vonovak** [comment]
hello. It's likely that the library you're relying on uses Modal from RN. This library relies on getting the presented ViewController which is the modal, when you're displaying the toast. Since the modal disappears, the toast which was shown using that Modal, disappears too. If you include a runnable repro, I could probably fix this somehow.

**Comment by vonovak** [comment]
closing as duplicate of https://github.com/vonovak/react-native-simple-toast/issues/11
