### ISSUE TITLE
Toast is displayed behind the keypad in iOS

### ISSUE THREAD

**Issue by Akshay577** [vonovak/react-native-simple-toast#62]
In iOS device, the toast message is displayed behind the keypad. Is it possible to display toast above the keypad?

**Comment by vonovak** [comment]
Hello and thanks for asking,
if you show the toast and then display the keyboard, then the toast will be hidden.
You need to display the keyboard first, and then display the toast.

Alternatively, we can make it so that whenever keyboard is shown / hidden, we update the toast position. I don't currently have time to work on this, but a PR is appreciated.

Thank you 🙂
